/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_eliak_VScoreNative */

#ifndef _Included_com_github_eliak_VScoreNative
#define _Included_com_github_eliak_VScoreNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_eliak_VScoreNative
 * Method:    cosineSimilarity
 * Signature: ([F[F)F
 */
JNIEXPORT jfloat JNICALL Java_com_github_eliak_VScoreNative_cosineSimilarity
  (JNIEnv *, jclass, jfloatArray, jfloatArray);

/*
 * Class:     com_github_eliak_VScoreNative
 * Method:    createScorerFactory
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_github_eliak_VScoreNative_createScorerFactory
  (JNIEnv *, jclass);

/*
 * Class:     com_github_eliak_VScoreNative
 * Method:    destroyScorerFactory
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_github_eliak_VScoreNative_destroyScorerFactory
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_eliak_VScoreNative
 * Method:    createScorer
 * Signature: (J[F)J
 */
JNIEXPORT jlong JNICALL Java_com_github_eliak_VScoreNative_createScorer
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     com_github_eliak_VScoreNative
 * Method:    destroyScorer
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_eliak_VScoreNative_destroyScorer
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_eliak_VScoreNative
 * Method:    score
 * Signature: (JILcom/github/eliak/VScoreNative/ScorerCallback;)F
 */
JNIEXPORT jfloat JNICALL Java_com_github_eliak_VScoreNative_score
  (JNIEnv *, jclass, jlong, jint, jobject);

/*
 * Class:     com_github_eliak_VScoreNative
 * Method:    identity
 * Signature: (F)F
 */
JNIEXPORT jfloat JNICALL Java_com_github_eliak_VScoreNative_identity
  (JNIEnv *, jclass, jfloat);

#ifdef __cplusplus
}
#endif
#endif
